name: release-library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pack dependencies
      run: docker build --tag publish --file Dockerfile.Pack .
    # - name: Publish
    #   run: docker run --rm publish --api-key ${{secrets.NUGETAPIKEY}} --source "https://api.nuget.org/v3/index.json"
